### ISSUE TITLE
RabbitMQ transport

### ISSUE THREAD

**Issue by taybin** [Nextdoor/pg-bifrost#16]
I'm working on a RabbitMQ transport, where messages would be published to an exchange, with a routing key of format `schema.table.operation`.  Is there interest in accepting this upstream when it's ready?

**Comment by stlava** [comment]
Absolutely! Once it's ready I'll see who can review it as I don't have operational experience with RabbitMQ. I encourage adding integration tests.

/cc @nehalrp

**Comment by taybin** [comment]
Great.  I'm almost done.  I have the performance where I like it (1 million messages in ~4 minutes, on my dev laptop).  I didn't add retry semantics (yet) because I wasn't sure what would be appropriate for RabbitMQ besides shutting the whole thing down and letting docker restart it.

Still working on the tests.  I'm not sure what refactorings will fall out of the testing, so I haven't pushed my branch yet.

**Comment by taybin** [comment]
PR here: https://github.com/Nextdoor/pg-bifrost/pull/19

**Comment by taybin** [comment]
Closing this as the PR was merged.
