### ISSUE TITLE
blacklist/whitelist accept regex

### ISSUE THREAD

**Issue by taybin** [Nextdoor/pg-bifrost#21]
Because of sharding with citus, my tables have names like `users_54326`, `users_24231`, etc.  The number of these is large, varies across worker nodes, and overall cumbersome to put them in the blacklist fields.  Would you accept a patch that allows regexs for table filtering so I could do something like `--blacklist="users.*"` or whatever the golang regex engine allows?

**Comment by stlava** [comment]
That sounds totally reasonable. The only reason why we didn't do that initially was because we didn't have that use case. It would be nice to have a flag to turn on/off the use of regex so if you know the tables there is no performance hit for unnecessarily doing a regex check.

**Comment by taybin** [comment]
How about a separate `--blacklist-regex` or `--regex-blacklist` option?  Not sure if the filtering should be the sum of --blacklist and --blacklist-regex or if they should be exclusive though.

**Comment by stlava** [comment]
There's a little bit of a disconnect with how the blacklist and whitelist are handled internally versus how they are presented to the user. To keep things consistent I suggest that a user is limited to only one of the following options `blacklist`, `blacklist-regex`, `whitelist`, or `whitelist-regex`.  In the filter module add a second param array for regex patterns and keep the flag that controls if it's inclusive or exclusive.

**Comment by taybin** [comment]
Sounds good.  I hadn't looked closely at the code yet.

**Comment by taybin** [comment]
@stlava ping

**Comment by taybin** [comment]
Closing since this was merged.

**Comment by taybin** [comment]
Actually, I'd like to keep this open until a new release has shipped with this.

**Comment by stlava** [comment]
Released `1.2.4`

**Comment by taybin** [comment]
Thank you!
