### ISSUE TITLE
transporters - kinesis - add IAM role support

### ISSUE THREAD

**Issue by nehalrp** [Nextdoor/pg-bifrost#35]
Similar to: https://github.com/Nextdoor/pg-bifrost/blob/262b4fafe1fe54357acf44d0e5270982c5235f6d/transport/transporters/s3/transporter/transporter.go#L135

**Comment by YOU54F** [comment]
hey @nehalrp are you happy for PR for this, as I think I need this change to run as an ECS task and stream to kinesis.

Thanks!
