### ISSUE TITLE
Should pg-bifrost exit when postgresql is shutting down?

### ISSUE THREAD

**Issue by taybin** [Nextdoor/pg-bifrost#45]
I've noticed that I need to manually terminate pg-bifrost when trying to shutdown postgres or it will block the database shutdown.  Is there a signal that is happening in the replication protocol and should pg-bifrost listen for it and respond?

**Comment by stlava** [comment]
I'm not aware of a signal that acts as a shutdown hook but will take a look. Re your case is your replication slot behind when you're doing a shutdown or it mostly caught up?

**Comment by taybin** [comment]
It should be caught up at that point.  This is for a scheduled shutdown.

**Comment by stlava** [comment]
For testing purposes what version of postgres are you using?

**Comment by taybin** [comment]
I'm using postgresql-10.7.

**Comment by stlava** [comment]
There isn't a shutdown hook handler in the postgres protocol docs. I think the two ways for the client to disconnect are either by the server terminating the connection or the client deciding that it has caught up and exit. We can introduce some logic into the client to decide that it has caught up and can exit but that may not be ideal depending on your write patterns. @nehalrp hasn't been able to reproduce the hanging shutdown scenario.

**Comment by taybin** [comment]
Thank you for investigating.  The exit-on-caught-up wouldn't be appropriate for my use case.  I can work around this with scripting.  I'm surprised he wasn't able to reproduce the scenario though.  I'll have to see if there's something weird about my own setup.  Thank you for your help.
